# Generated by Django 2.0.7 on 2018-08-08 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CVE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cvss_v3', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('severity', models.CharField(max_length=20)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('affected_package', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('current_version', models.CharField(max_length=255)),
                ('new_version', models.CharField(max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SSHProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssh_server_address', models.CharField(blank=True, max_length=255)),
                ('ssh_server_port', models.PositiveSmallIntegerField(blank=True, default=22)),
                ('ssh_username', models.CharField(blank=True, max_length=255)),
                ('ssh_key', models.FileField(upload_to='uploaded_keys/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('connected', models.BooleanField(default=True)),
                ('system_os_name', models.CharField(max_length=255)),
                ('system_os_version', models.CharField(max_length=255)),
                ('system_kernel', models.CharField(max_length=255)),
                ('system_package_manager', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('task_name', models.CharField(max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('is_notified', models.BooleanField(default=False)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='patch_management.System'),
        ),
        migrations.AddField(
            model_name='cve',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cves', to='patch_management.System'),
        ),
        migrations.AlterUniqueTogether(
            name='system',
            unique_together={('hostname', 'owner')},
        ),
        migrations.AlterUniqueTogether(
            name='package',
            unique_together={('name', 'system')},
        ),
        migrations.AlterUniqueTogether(
            name='cve',
            unique_together={('cve_id', 'system')},
        ),
    ]
