# Generated by Django 2.0.7 on 2018-07-24 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('current_version', models.CharField(max_length=255)),
                ('new_version', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('connected', models.BooleanField(default=False)),
                ('server_os', models.CharField(max_length=255)),
                ('server_version', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SSHProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssh_server_address', models.CharField(blank=True, max_length=255)),
                ('ssh_server_port', models.PositiveSmallIntegerField(blank=True, default=22)),
                ('ssh_username', models.CharField(blank=True, max_length=30)),
                ('ssh_key', models.FileField(upload_to='uploaded_keys/')),
                ('ssh_passphase', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='patch_management.Server'),
        ),
        migrations.AlterUniqueTogether(
            name='server',
            unique_together={('hostname', 'owner')},
        ),
    ]
