# Generated by Django 2.0.7 on 2018-07-17 22:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patch_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSshProfile',
            new_name='Profile',
        ),
    ]
