# Generated by Django 2.0.7 on 2018-07-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patch_management', '0004_mymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersshprofile',
            old_name='server_address',
            new_name='ssh_passphase',
        ),
        migrations.AddField(
            model_name='usersshprofile',
            name='ssh_server_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
