# Generated by Django 2.0.7 on 2018-07-20 17:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patch_management', '0005_auto_20180720_1825'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSSHProfile',
            new_name='SSHProfile',
        ),
    ]
