# Generated by Django 2.0.7 on 2018-07-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patch_management', '0006_auto_20180720_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='sshprofile',
            name='ssh_server_port',
            field=models.PositiveSmallIntegerField(blank=True, default=22),
        ),
    ]
